name: azul_ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.19.2
  - tensorflow>=2.4.0
  - pytorch>=1.9.0
  - pygame>=2.0.1
  - matplotlib>=3.3.2
  - pytest>=6.2.4
  - jupyter
  - pip
  - pip:
    - gym>=0.21.0
    - stable-baselines3>=1.5.0 