name: azul-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9
  - numpy=1.21
  - pygame=2.1
  - pytest
  - black
  - flake8
  - jupyter
  - matplotlib
  - tqdm
  - pip
  - pip:
    - gymnasium==0.29.1 